GET http://localhost:4000/api/files 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzIwNzI2OTcsImV4cCI6MTY3MjA3MjcyN30.fab6bRjO_siWdTMunYfERo0kWzJo3b7puv29rmEgxR4

###

POST http://localhost:4000/api/token
content-type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWRmZmY1ZmRkZGZkYWZmZ0BnbWFpbC5jb20iLCJpYXQiOjE2NzIwNzI2NTR9.OpqoHraBg32lHYFKEdnNLE1Irn5hL0wY1eb1mb5hK5I"
}
###
POST http://localhost:4000/api/register
content-type: application/json

  {
  "email":"mdfff5fdddfdaffg@gmail.com",
  "password":"zmadkf343DSDS21"
  } 
