name: testing app
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: testing frontend
        working-directory: ./frontend
        run: npm build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get repository
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
