name: test
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Print the input tag to STDOUT
      run: echo Hi guys!
    - name: another one job
      run: echo first line 
           echo second line
